title: Behind The Beat
description: Heartfelt Reviews & Introspective Interviews.
url: "https://eshaansoood.github.io"
baseurl: "/brbpodcast"
# GitHub Pages will set the correct baseurl at build time if using Pages.
# Ensure all links use relative_url filter in Liquid where applicable.
permalink: pretty
markdown: kramdown

collections:
  reviews:
    output: true
    permalink: /reviews/:path/
  podcasts:
    output: true
    permalink: /podcasts/:path/

defaults:
  - scope:
      path: ""
      type: reviews
    values:
      layout: entry
  - scope:
      path: ""
      type: podcasts
    values:
      layout: entry

exclude:
  - node_modules
  - theme.zip
  - README.md
  - .DS_Store
  - __MACOSX
  - .bundle
  - .git

